### PR TITLE
Fix TCK body reading inconsistency

### LINKED ISSUE #375: HTTP Server TCK MiscTest fails
### Issue description

https://github.com/micronaut-projects/micronaut-servlet/blob/3.4.x/test-suite-http-server-tck-jetty/src/test/java/io/micronaut/http/server/tck/jetty/tests/JettytHttpServerTestSuite.java#L11

### PR DESCRIPTION
**Pull request by graemerocher**
Fixes #375

### CODE REVIEW

**Comment by graemerocher** [comment]
Replaced by https://github.com/micronaut-projects/micronaut-servlet/pull/393

File: servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpRequest.java [hunk 1]
```diff
@@ -138,6 +150,101 @@ protected DefaultServletHttpRequest(ConversionService conversionService,
...
+
+    private Object decode(InputStream inputStream, MediaTypeCodec codec) throws IOException {
+        return codec.decode(Argument.of(byte[].class), inputStream);
+    }
+
+    private Object readJson(InputStream inputStream, MapperMediaTypeCodec mapperCodec) throws IOException {
+        return mapperCodec.getJsonMapper().readValue(inputStream, Argument.of(JsonNode.class));
+    }
+
+    private byte[] readAll(InputStream inputStream) throws IOException {
```
Comment (yawkat) [inline servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpRequest.java:236]: theres a method to do this on inputstream now

**Review by yawkat — APPROVED** [review]
