### PR TITLE
Fix for NPE when no cookies set on request

### LINKED ISSUE #52: NullpointerException on Filter when there is no cookie on the request
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a filter in Kotlin using `@Filter` annotation
2. Get the request cookie by request.cookies
3. Try to verify if there is cookies by request.cookies.isEmpty
4. If the request does not have any cookie a NullpointerException is thrown

### Expected Behaviour

When the request does not have any cookie the `request.cookies.isEmpty` call should return true or `request.cookies` should be null

### Actual Behaviour

When the request does not have any cookie `request.cookies` is not null and calling `request.cookies.isEmpty` throws a NullpointerException

### Environment Information

- **Operating System**: Fedora 30
- **Micronaut Version:** 2.0.0
- **Servlet Micronaut Version:** 1.0.2
- **JDK Version:** 11

### Example Application

```Kotlin
@Filter(Filter.MATCH_ALL_PATTERN)
class SomeFilter() : HttpServerFilter {
    override fun doFilter(request: HttpRequest<*>, chain: ServerFilterChain): Publisher<MutableHttpResponse<*>> {
        val cookies: Cookies = req.cookies

        if (cookies.isEmpty) {
           println("Cookies are empty!")
        }

        return chain.proceed(request)
    }
}
```

### LINKED ISSUE #71: NullPointerException is thrown when no cookie is available in the servlet request - tomcat server
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1.  Follow the steps detailed in Micronaut Security JWT guide or download the completed source code
https://guides.micronaut.io/micronaut-security-jwt/guide/index.html
https://github.com/micronaut-guides/micronaut-security-jwt/archive/master.zip
2. Test run using netty server (default) - API works as detailed in the document
3. Change the netty server to tomcat server dependencies in build.gradle
replace 
    implementation("io.micronaut:micronaut-http-server-netty")
with
    implementation("io.micronaut.servlet:micronaut-http-server-tomcat:2.0.0")

4. Execute the POST API
POST http://localhost:8080/login
POST /login HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.26.5
Accept: */*
Postman-Token: a88b8ab0-a1cf-46da-b3b1-fa3315066b26
Host: localhost:8080
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 58
{
    "username": "sherlock",
    "password": "password"
}

### Expected Behaviour

Reponse should be 

HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 277
Date: Wed, 30 Sep 2020 13:35:03 GMT
Keep-Alive: timeout=60
Connection: keep-alive
{"username":"sherlock","access_token":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzaGVybG9jayIsIm5iZiI6MTYwMTQ3MjkwMywicm9sZXMiOltdLCJpc3MiOiJtaWNyb25hdXQiLCJleHAiOjE2MDE0NzY1MDMsImlhdCI6MTYwMTQ3MjkwM30.abyDHD17rJQEv-2dZYQdTFYsWh7DlcOFVDq3KCWsjxA","token_type":"Bearer","expires_in":3600}

### Actual Behaviour

Response is 

HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 30 Sep 2020 13:33:01 GMT
Connection: close
{"_links":{"self":{"href":"/login","templated":false}}}

We get null pointer exception. 

18:47:25.379 [http-nio-8080-exec-4] ERROR i.m.servlet.http.ServletHttpHandler - Internal Server Error: null
java.lang.NullPointerException: null
	at io.micronaut.servlet.engine.DefaultServletCookies.findCookie(DefaultServletCookies.java:54)
	at io.micronaut.security.token.jwt.cookie.JwtCookieTokenReader.findToken(JwtCookieTokenReader.java:55)
	at io.micronaut.security.token.reader.DefaultTokenResolver.lambda$resolveToken$0(DefaultTokenResolver.java:57)

### Work around
Put some dummy cookie in the header and submit.  Request will be successful

POST http://localhost:8080/login
200
9 ms
POST /login HTTP/1.1
**Cookie: Cookie_2=value; Path=/; Domain=.reqres.in; Expires=Thu, 30 Sep 2021 13:19:46 GMT;**
Content-Type: application/json
User-Agent: PostmanRuntime/7.26.5
Accept: */*
Postman-Token: a0e18f70-5ba2-4a56-beb9-a22b232c3e51
Host: localhost:8080
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 58
{
    "username": "sherlock",
    "password": "password"
}

### Environment Information

- **Operating System**: Ubuntu 18
- **Micronaut Version:** 2.0.3
- **JDK Version:** 1.8

### Example Application

https://github.com/micronaut-guides/micronaut-security-jwt

### PR DESCRIPTION
**Pull request by ilopmar**
Fixes #52 Fixes #71

### CODE REVIEW

File: servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletCookies.java [hunk 1]
```diff
@@ -38,7 +42,11 @@
      * @param cookies The cookies
      */
     public DefaultServletCookies(javax.servlet.http.Cookie[] cookies) {
-        this.cookies = cookies;
+        if (cookies == null) {
+            this.cookies = new javax.servlet.http.Cookie[]{};
```
Comment (graemerocher) [inline servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletCookies.java:46]: This should be `this.cookies = new javax.servlet.http.Cookie[0]` to avoid the array initializer and be extracted to a constant

**Review by graemerocher — CHANGES_REQUESTED** [review]

File: servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletCookies.java (hunk 1 above)
Comment (ilopmar) [reply servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletCookies.java]: Done

**Comment by graemerocher** [comment]
Weird new failures happening 🤔

**Comment by ilopmar** [comment]
I've found the issue of the failures in master branch. The test certificate has expired :scream: https://github.com/micronaut-projects/micronaut-servlet/issues/75
